spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          wso2:
            client-id: JmOyV0nHeR0tGYwDG2SYyphgMDAa
            client-secret: Epr5tlxr8UGac11PZgpYIjlWR68a
        provider:
          wso2:
            authorization-uri: https://auth.nerves-cloud.com:9443/oauth2/authorize
            token-uri: https://auth.nerves-cloud.com:9443/oauth2/token
            user-info-uri: https://auth.nerves-cloud.com:9443/oauth2/userinfo
            jwk-set-uri: https://auth.nerves-cloud.com:9443/oauth2/jwks

params: 
   trustStorePath: /ca-keys/client-truststore.jks
   trustStorePassword: wso2carbon
   keyStorePath: /ca-keys/wso2carbon.jks
   keyStorePassword: wso2carbon
   defaultType: JKS